action_id: trunk-single-player-auto-upgrade
date: 2025-12-12 17:12:08
run: trunk upgrade cli --single-player-only -n --no-progress --on-upgrade=false --allow-daemon-start=false
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1765559528
full_timestamp:
  nanos: 305945000
  seconds: 1765559528
trunk_version: 1.25.0
