action_id: trunk-cache-prune
date: 2025-12-10 19:24:04
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1765394644
full_timestamp:
  nanos: 463315000
  seconds: 1765394644
trunk_version: 1.25.0
