action_id: trunk-cache-prune
date: 2025-12-13 13:23:58
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1765632238
full_timestamp:
  nanos: 497672000
  seconds: 1765632238
trunk_version: 1.25.0
