action_id: trunk-cache-prune
date: 2025-12-10 20:23:39
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1765398219
full_timestamp:
  nanos: 279529000
  seconds: 1765398219
trunk_version: 1.25.0
