/**
 * Recipe Assistant - Hands-free cooking helper
 * 
 * Endpoints:
 * - POST /search     - Search web for recipes
 * - POST /start      - Start a recipe (stores in short-term memory)
 * - POST /step       - Get current step / navigate ("next", "prev", "repeat")
 * - POST /timer      - Set a timer via Home Assistant
 * - GET  /active     - Get active recipe for connection
 * - DELETE /clear    - Clear active recipe
 */

import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "npm:@supabase/supabase-js@2.38.4"

const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
}

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!

// Google Custom Search (100 free/day)
const GOOGLE_API_KEY = Deno.env.get("GOOGLE_API_KEY") || "";
const GOOGLE_CSE_ID = Deno.env.get("GOOGLE_CSE_ID") || "";  // Custom Search Engine ID

// Gemini for recipe generation (generous free tier)
const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY") || Deno.env.get("GOOGLE_API_KEY") || "";

interface Recipe {
    name: string;
    servings: number;
    prepTime: string;
    cookTime: string;
    ingredients: string[];
    steps: string[];
    currentStep: number;
    source?: string;
    modifications?: string[];
}

function jsonResponse(data: any, status = 200) {
    return new Response(JSON.stringify(data), {
        status,
        headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
}

// Search the web for recipes using Google Custom Search
async function searchRecipes(query: string): Promise<any[]> {
    if (GOOGLE_API_KEY && GOOGLE_CSE_ID) {
        try {
            const searchQuery = encodeURIComponent(`recipe ${query}`);
            const url = `https://www.googleapis.com/customsearch/v1?key=${GOOGLE_API_KEY}&cx=${GOOGLE_CSE_ID}&q=${searchQuery}&num=5`;

            const response = await fetch(url);

            if (response.ok) {
                const data = await response.json();
                console.log(`[Recipe] Google search found ${data.items?.length || 0} results`);
                return data.items?.map((item: any) => ({
                    title: item.title,
                    url: item.link,
                    snippet: item.snippet?.substring(0, 200)
                })) || [];
            } else {
                console.error('[Recipe] Google search failed:', await response.text());
            }
        } catch (e) {
            console.error('[Recipe] Google search error:', e);
        }
    } else {
        console.log('[Recipe] No Google API keys, using LLM generation only');
    }

    return [];
}

// Use Gemini Flash to generate recipe (better for creative/culinary tasks)
async function generateRecipe(query: string, webResults: any[]): Promise<Recipe> {
    const webContext = webResults.length > 0
        ? `I found these recipes online for inspiration:\n${webResults.map(r => `- ${r.title}: ${r.snippet}`).join('\n')}\n\nUse these as reference but create a complete, accurate recipe.`
        : 'Generate this recipe from your culinary knowledge. Be accurate with measurements and cooking times.';

    const prompt = `You are a professional chef. Create a detailed, accurate recipe for: "${query}"

${webContext}

Return ONLY valid JSON in this exact format (no markdown, no explanation):
{
    "name": "Recipe Name",
    "servings": 4,
    "prepTime": "15 minutes",
    "cookTime": "30 minutes",
    "ingredients": ["200g pasta", "4 eggs", "100g parmesan"],
    "steps": [
        "Step 1: Boil water and cook pasta according to package.",
        "Step 2: While pasta cooks, whisk eggs with parmesan.",
        "Step 3: ..."
    ],
    "source": "${webResults.length > 0 ? 'Inspired by online recipes' : 'Generated by chef AI'}"
}`;

    // Try Gemini Flash first (better for creative tasks)
    if (GEMINI_API_KEY) {
        try {
            const response = await fetch(
                `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.0-flash:generateContent?key=${GEMINI_API_KEY}`,
                {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        contents: [{ parts: [{ text: prompt }] }],
                        generationConfig: {
                            temperature: 0.7,
                            maxOutputTokens: 2000
                        }
                    })
                }
            );

            if (response.ok) {
                const data = await response.json();
                const content = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
                console.log('[Recipe] Gemini response received');

                // Extract JSON from response
                const jsonMatch = content.match(/\{[\s\S]*\}/);
                if (jsonMatch) {
                    const recipe = JSON.parse(jsonMatch[0]);
                    recipe.currentStep = 0;
                    return recipe as Recipe;
                }
            } else {
                console.error('[Recipe] Gemini failed:', await response.text());
            }
        } catch (e) {
            console.error('[Recipe] Gemini error:', e);
        }
    }

    // Fallback to Groq if Gemini fails
    const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY");
    if (GROQ_API_KEY) {
        const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${GROQ_API_KEY}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                model: 'llama-3.3-70b-versatile',
                messages: [{ role: 'user', content: prompt }],
                max_tokens: 1500,
                temperature: 0.7
            })
        });

        if (response.ok) {
            const data = await response.json();
            const content = data.choices[0]?.message?.content || '';
            const jsonMatch = content.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
                const recipe = JSON.parse(jsonMatch[0]);
                recipe.currentStep = 0;
                return recipe as Recipe;
            }
        }
    }

    throw new Error('Failed to generate recipe - no LLM available');
}

Deno.serve(async (req: Request) => {
    if (req.method === "OPTIONS") {
        return new Response(null, { headers: corsHeaders });
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const url = new URL(req.url);
    const path = url.pathname.replace('/recipe-assistant', '');

    try {
        const body = req.method !== 'GET' && req.method !== 'DELETE' ? await req.json() : {};
        const connectionId = url.searchParams.get('connection_id') || body.connection_id;

        if (!connectionId) {
            return jsonResponse({ error: 'connection_id required' }, 400);
        }

        // =============================================
        // POST /search - Search for recipes
        // =============================================
        if (path === '/search' && req.method === 'POST') {
            const query = body.query;
            if (!query) return jsonResponse({ error: 'query required' }, 400);

            console.log(`[Recipe] Searching for: ${query}`);

            const webResults = await searchRecipes(query);
            const recipe = await generateRecipe(query, webResults);

            return jsonResponse({
                success: true,
                recipe,
                webSources: webResults.slice(0, 3)
            });
        }

        // =============================================
        // POST /start - Start cooking a recipe
        // =============================================
        if (path === '/start' && req.method === 'POST') {
            const recipe = body.recipe as Recipe;
            if (!recipe) return jsonResponse({ error: 'recipe required' }, 400);

            recipe.currentStep = 0;

            // Store in short-term memory (expires in 6 hours for cooking)
            const expiresAt = new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString();

            // Clear any existing active recipe first
            await supabase
                .from('short_term_memory')
                .delete()
                .eq('connection_id', connectionId)
                .eq('context_type', 'recipe');

            // Insert new recipe
            await supabase.from('short_term_memory').insert({
                connection_id: connectionId,
                context_type: 'recipe',
                context_key: recipe.name,
                data: recipe,
                expires_at: expiresAt
            });

            console.log(`[Recipe] Started: ${recipe.name} (${recipe.steps.length} steps)`);

            return jsonResponse({
                success: true,
                message: `Recipe "${recipe.name}" loaded! You have ${recipe.ingredients.length} ingredients and ${recipe.steps.length} steps.`,
                currentStep: 1,
                totalSteps: recipe.steps.length,
                firstStep: recipe.steps[0],
                ingredients: recipe.ingredients
            });
        }

        // =============================================
        // POST /step - Navigate recipe steps
        // =============================================
        if (path === '/step' && req.method === 'POST') {
            const action = body.action || 'current';  // 'next', 'prev', 'repeat', 'current', or step number

            // Get active recipe
            const { data: memory } = await supabase
                .from('short_term_memory')
                .select('*')
                .eq('connection_id', connectionId)
                .eq('context_type', 'recipe')
                .single();

            if (!memory) {
                return jsonResponse({
                    success: false,
                    message: "No active recipe. Say 'find me a recipe for...' to start."
                });
            }

            const recipe = memory.data as Recipe;
            let newStep = recipe.currentStep;

            if (action === 'next') {
                newStep = Math.min(recipe.currentStep + 1, recipe.steps.length - 1);
            } else if (action === 'prev' || action === 'previous' || action === 'back') {
                newStep = Math.max(recipe.currentStep - 1, 0);
            } else if (typeof action === 'number' || !isNaN(parseInt(action))) {
                newStep = Math.max(0, Math.min(parseInt(action) - 1, recipe.steps.length - 1));
            }

            // Update step in memory
            recipe.currentStep = newStep;
            await supabase
                .from('short_term_memory')
                .update({ data: recipe, updated_at: new Date().toISOString() })
                .eq('id', memory.id);

            const isLastStep = newStep === recipe.steps.length - 1;

            return jsonResponse({
                success: true,
                recipeName: recipe.name,
                currentStep: newStep + 1,
                totalSteps: recipe.steps.length,
                stepText: recipe.steps[newStep],
                isLastStep,
                message: isLastStep
                    ? `Final step! ${recipe.steps[newStep]}`
                    : `Step ${newStep + 1} of ${recipe.steps.length}: ${recipe.steps[newStep]}`
            });
        }

        // =============================================
        // POST /timer - Set a cooking timer via HA
        // =============================================
        if (path === '/timer' && req.method === 'POST') {
            const minutes = body.minutes || body.duration;
            const label = body.label || 'Cooking timer';

            if (!minutes) return jsonResponse({ error: 'minutes required' }, 400);

            // Get HA connection
            const { data: conn } = await supabase
                .from('ha_connections')
                .select('api_url, api_token')
                .eq('id', connectionId)
                .single();

            if (conn) {
                try {
                    // Set timer via HA
                    await fetch(`${conn.api_url}/api/services/timer/start`, {
                        method: 'POST',
                        headers: {
                            'Authorization': `Bearer ${conn.api_token}`,
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            duration: `00:${String(minutes).padStart(2, '0')}:00`
                        })
                    });
                } catch (e) {
                    console.error('[Recipe] Timer failed:', e);
                }
            }

            // Also store timer in short-term memory as backup
            const expiresAt = new Date(Date.now() + minutes * 60 * 1000).toISOString();
            await supabase.from('short_term_memory').insert({
                connection_id: connectionId,
                context_type: 'timer',
                context_key: label,
                data: { minutes, label, startedAt: new Date().toISOString() },
                expires_at: expiresAt
            });

            return jsonResponse({
                success: true,
                message: `Timer set for ${minutes} minutes: ${label}`
            });
        }

        // =============================================
        // GET /active - Get active recipe
        // =============================================
        if (path === '/active' && req.method === 'GET') {
            const { data: memory } = await supabase
                .from('short_term_memory')
                .select('*')
                .eq('connection_id', connectionId)
                .eq('context_type', 'recipe')
                .single();

            if (!memory) {
                return jsonResponse({ active: false });
            }

            const recipe = memory.data as Recipe;
            return jsonResponse({
                active: true,
                recipe,
                currentStep: recipe.currentStep + 1,
                totalSteps: recipe.steps.length,
                currentStepText: recipe.steps[recipe.currentStep]
            });
        }

        // =============================================
        // DELETE /clear - Clear active recipe
        // =============================================
        if (path === '/clear' && req.method === 'DELETE') {
            await supabase
                .from('short_term_memory')
                .delete()
                .eq('connection_id', connectionId)
                .eq('context_type', 'recipe');

            return jsonResponse({ success: true, message: 'Recipe cleared' });
        }

        return jsonResponse({ error: 'Endpoint not found', path }, 404);

    } catch (err: any) {
        console.error('[Recipe] Error:', err);
        return jsonResponse({ error: err.message }, 500);
    }
});
