@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\jensv\AppData\Local\trunk\tools\osv-scanner\2.3.1-cc0bf0b8c179c6999024e4901b7b70d8;C:\Users\jensv\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\jensv\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
