@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\jensv\AppData\Local\trunk\tools\trufflehog\3.92.3-1cfbe64db1a40343dc16e8ce20c499f6;C:\Users\jensv\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\jensv\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
