action_id: trunk-upgrade-available
date: 2025-12-14 00:24:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: eccc742495a445019fd5d4fee38e7910)\x1b[0m\r\n"
  err: ""
timestamp: 1765671845
full_timestamp:
  nanos: 837406000
  seconds: 1765671845
trunk_version: 1.25.0
