action_id: trunk-upgrade-available
date: 2025-12-13 17:24:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: aa8978bce1e240e1f822b393d70baafb)\x1b[0m\r\n"
  err: ""
timestamp: 1765646645
full_timestamp:
  nanos: 721333000
  seconds: 1765646645
trunk_version: 1.25.0
