action_id: trunk-upgrade-available
date: 2025-12-14 03:24:03
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 7e0b16b6b4af413f9a47f39f334eb124)\x1b[0m\r\n"
  err: ""
timestamp: 1765682643
full_timestamp:
  nanos: 246566000
  seconds: 1765682643
trunk_version: 1.25.0
