action_id: trunk-upgrade-available
date: 2025-12-13 23:24:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: fc630f06796e464d994a17d14d10bf8f)\x1b[0m\r\n"
  err: ""
timestamp: 1765668245
full_timestamp:
  nanos: 746088000
  seconds: 1765668245
trunk_version: 1.25.0
