action_id: trunk-upgrade-available
date: 2025-12-14 02:24:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 7ea8cef4039e402d2b5c9ea03e59952a)\x1b[0m\r\n"
  err: ""
timestamp: 1765679045
full_timestamp:
  nanos: 981248000
  seconds: 1765679045
trunk_version: 1.25.0
