action_id: trunk-upgrade-available
date: 2025-12-11 00:28:50
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 0
  out: "notifications_to_delete:\r\n  - trunk-check-upgrade\r\n  - trunk-upgrade\r\n"
  err: ""
timestamp: 1765412930
full_timestamp:
  nanos: 413460000
  seconds: 1765412930
trunk_version: 1.25.0
action_output:
  notifications_to_delete:
    - trunk-check-upgrade
    - trunk-upgrade
