action_id: trunk-upgrade-available
date: 2025-12-13 16:24:06
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: e71c001ac02a4a777cd548d50444b467)\x1b[0m\r\n"
  err: ""
timestamp: 1765643046
full_timestamp:
  nanos: 287112000
  seconds: 1765643046
trunk_version: 1.25.0
