action_id: trunk-upgrade-available
date: 2025-12-14 01:24:05
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 43e21f193aea40c4351ebd5b6d2c39a8)\x1b[0m\r\n"
  err: ""
timestamp: 1765675445
full_timestamp:
  nanos: 851991000
  seconds: 1765675445
trunk_version: 1.25.0
