action_id: trunk-upgrade-available
date: 2025-12-14 04:24:03
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2
  out: "\x1b[1m\x1b[31m✖ Trunk Internal Error: Please report this issue at https://slack.trunk.io (reference id: 036a8cba82f141a0f2763e63d930a6c5)\x1b[0m\r\n"
  err: ""
timestamp: 1765686243
full_timestamp:
  nanos: 208414000
  seconds: 1765686243
trunk_version: 1.25.0
