
-- Ensure table exists
create table if not exists scheduler_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    level text default 'info',
    message text,
    details jsonb
);

-- Enable RLS
alter table scheduler_logs enable row level security;

-- Policies
-- Policies
drop policy if exists "Allow insert for service role" on scheduler_logs;
create policy "Allow insert for service role" on scheduler_logs 
for insert with check (true);

drop policy if exists "Allow select for authenticated" on scheduler_logs;
create policy "Allow select for authenticated" on scheduler_logs 
for select using (true);

-- NEW: Allow anon to read logs (for debug mode in app)
drop policy if exists "Allow select for anon" on scheduler_logs;
create policy "Allow select for anon" on scheduler_logs 
for select using (true);

-- Allow anon to insert? No, only service role (Edge Functions) should insert.
