-- Create a table to log scheduler activity for easier debugging
create table if not exists scheduler_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    level text default 'info',
    message text,
    details jsonb
);

-- Policy (Open for now/internal use)
alter table scheduler_logs enable row level security;

drop policy if exists "Allow insert for service role" on scheduler_logs;
create policy "Allow insert for service role" on scheduler_logs for insert with check (true);

drop policy if exists "Allow select for authenticated" on scheduler_logs;
create policy "Allow select for authenticated" on scheduler_logs for select using (true);
